name: Go API CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: servidor

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install dependencies
        run: go mod tidy

      - name: Build application
        run: go build ./...

      - name: Run tests
        run: go test ./...
